---

- name: "Yarn | Uninstall globally installed packages"
  shell: "yarn global remove {{ item.name }}@{{ item.version | default('') }} --PREFIX={{ yarn_global_path }}"
  failed_when: false
  with_items:
    - "{{ yarn_global_packages }}"
  changed_when: false
  when: yarn_clean_install == true

- name: "Yarn | Get list of globally installed packages"
  shell: "yarn global list"
  register: yarn_global_ls
  failed_when: false
  changed_when: false

- name: "Yarn | Add globally installed packages"
  shell: "yarn global add {{ item.name }}@{{ item.version | default('') }} --PREFIX={{ yarn_global_path }}"
  when:
    - item.name + '@' + item.version not in yarn_global_ls.stdout
  with_items:
    - "{{ yarn_global_packages }}"

- name: "Yarn | Upgrade installed packages"
  shell: "yarn global upgrade {{ item.name }} --PREFIX={{ yarn_global_path }}"
  when:
    - item.upgrade is defined
    - item.upgrade|bool == true
  with_items:
    - "{{ yarn_global_packages }}"