---

- name: "Yarn | De-configure shell profiles"
  lineinfile:
    dest: "/home/{{ fubarhouse_user }}/{{ item }}"
    regexp: "PATH:{{ yarn_global_path }}/bin"
    line:  'export PATH="$PATH:{{ yarn_global_path }}/bin";'
    state: present
  failed_when: false
  with_items:
    - "{{ yarn_shell_profiles }}"
  when: yarn_clean_install == true

- name: "Yarn | Uninstall"
  package:
    name: yarn
    state: absent
  when: 'yarn_clean_install == true and "{{ ansible_os_family }}" == "Debian" or "{{ ansible_os_family }}" == "RedHat"'

- name: "Yarn | Include OS-specific tasks"
  include: "yarn-{{ ansible_os_family }}.yml"
  when: '"{{ ansible_os_family }}" == "Debian" or "{{ ansible_os_family }}" == "RedHat"'

- name: "Yark | Check for installation"


- name: "Yarn | Install"
  package:
    name: yarn
    state: latest
  when: '"{{ ansible_os_family }}" == "Debian" or "{{ ansible_os_family }}" == "RedHat"'

- name: "Yarn | Configure shell profiles"
  lineinfile:
    dest: "/home/{{ fubarhouse_user }}/{{ item }}"
    regexp: "PATH:{{ yarn_global_path }}/bin"
    line:  'export PATH="$PATH:{{ yarn_global_path }}/bin";'
    state: present
  failed_when: false
  with_items:
    - "{{ yarn_shell_profiles }}"

- name: "Yarn | Ensure installed"
  shell: "which yarn"

- name: "Yarn | Update as required"
  shell: "yarn self-update {{ yarn_version | default() }}"
  when: 'yarn_update == true'
  failed_when: false